
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EmployeeDataAcces
{

using System;
    using System.Collections.Generic;
    // Følgende modelklasse mapper (passer) med tabellen ElevTable i Elever databasen i mssql.
public partial class ElevTable
{

    public int userID { get; set; }

    public string fornavn { get; set; }

    public string efternavn { get; set; }

    public string brugernavn { get; set; }

    public string password { get; set; }

    public string magnetstribe { get; set; }

    public string magnet_crypt { get; set; }

    public string status { get; set; }

    public Nullable<System.DateTime> tjekind_timestamp { get; set; }

    public string user_level { get; set; }

    public string iSKP { get; set; }

    public string bemning { get; set; }

    public string debug { get; set; }

    public Nullable<int> system_id { get; set; }

}

}
