

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EmployeeDataAcces
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

    // DbContext is an important class in Entity Framework API. It is a bridge between your domain or entity classes and the database.
    // DbContext er tilstede i System.Data.Entity; namespace.
    // Pointen med EleverEntities klassen er at skabe en forbindelse til databasen. 
    public partial class EleverEntities : DbContext
    {
        public EleverEntities()
            : base("name=EleverEntities")
        {

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        // DBset af type ElevTable -> (Tabel Model)
        public virtual DbSet<ElevTable> ElevTables { get; set; }

    }

}

