//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDataAcces
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    // Denne klasse hjælper os med at forbinde til databasen og hente elev enheder 
    public partial class EleverEntities : DbContext
    {
        public EleverEntities()
            : base("name=EleverEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        // Et Dbset representere en collection af alle enheder i Elev Tabbelen 
        public virtual DbSet<ElevTable> ElevTables { get; set; }
    }
}
